### ISSUE TITLE
Does not install all dependencies on Raspbian 10 - Buster

### ISSUE THREAD

**Issue by simongliddon** [chad-ermacora/rp-network-testers#10]
I just downloaded a fresh install of Raspbian Buster and tried to install the kootnetNetworkTesters.deb package and it installs but the application will not run. On closer inspection, the python module gevent is not building successfully because of a missing dependency libffi-dev but I don't know if this is just specific to this image. I'm using the full desktop release of raspbian but it appears it will require at least build-essential libssl-dev libffi-dev python-dev of which libffi-dev is the only one not included in this image. Can this be added to the dependencies?

**Comment by chad-ermacora** [comment]
It just worked for me.  You might have to update your apt-get list first with 
`sudo apt-get update`
If the list is out of date, and one of the required modules has been updated since the list was updated, it can't find the old version of the module to download and install.  I have been looking for a way to get the deb installer to update that list before installing, but I have not found it yet outside of using the command line.  

Let me know if that works for you.

**Comment by simongliddon** [comment]
I ran the `sudo apt-get update` before attempting the install but it maybe something I did. I'm still green in the use of linux but I got it to run after first doing `sudo apt install libffi-dev` Anyway I got it to install and have got it working so thank you and thanks for this great project.

**Comment by chad-ermacora** [comment]
Ahh, the random oddities.  Although I heard there are a lot more Pi's being sold for projects due to many people having to stay at home with COVID-19.  There is a chance one of the downloads (libffi-dev) randomly timed out. 

Thanks for the thanks :)
